baseurl: /jinguodong-blog
markdown: rdiscount
permalink: /:year/:month/:title/
url: /jinguodong-blog
author: guodong.j
pygments: true
paginate: 24
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
